/// Flutter icons VinaArgoIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VinaArgoIcon
///      fonts:
///       - asset: fonts/VinaArgoIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class VinaArgoIcon {
  VinaArgoIcon._();

  static const _kFontFam = 'VinaArgoIcon';
  static const _kFontPkg = null;

  static const IconData an_toan_sinh_hoc = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ban_hang_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danh_gia_giong = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danh_gia_noi_bo = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danh_gia_trang_trai_chan_nuoi = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gan_ma_vach = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mua_con_giong = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mua_thuc_an_thuoc_vacxin = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mua_vat_tu_va_dung_cu_chan_nuoi = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quan_ly_chat_thai_va_bvmt = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quan_ly_dot_nuoi = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tien_hanh_thu_hoach_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tron_bao_quan_va_phan_phoi_thuc_an = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ve_sinh_sat_trung = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xu_ly_dich_benh_1 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xu_ly_khieu_nai_1 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danh_gia_giong_1 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danh_gia_noi_bo_1 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danhgia_vung_sx_dat_nuoc = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gan_ma_vach_1 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mua_giong = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mua_may_moc_thiet_bi = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mua_phan_bon_va_chat_phu_gia = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mua_thuoc_bvtv = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quan_ly_mua_vu = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData su_dung_phan_bon_va_chat_phu_gia = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tien_hanh_thu_hoach = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tuoi_nuoc = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xu_ly_dich_benh = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xu_ly_khieu_nai = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ban_hang = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
